apiVersion: apps/v1
kind: Deployment
metadata:
  name: deso-destination
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: destination
  template:
    metadata:
      labels:
        app: destination
    spec:
      containers:
      - name: destination-container
        image: r.deso.tech/whoami/whoami
